/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'User' at '9/29/16 4:24 PM' with Gradle 2.14.1
 *
 * @author User, @date 9/29/16 4:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
